// =============================================================================
//    Copyright (c) 2025 - 2026 Haixing Hu.
//
//    SPDX-License-Identifier: Apache-2.0
//
//    Licensed under the Apache License, Version 2.0.
// =============================================================================

use proc_macro2::Span;

use super::field_name::FieldName;

/// Parsed primary-key syntax.
pub(crate) struct PrimaryKeyAttribute {
    /// Fields in key order.
    pub(crate) fields: Vec<FieldName>,
    /// Fields whose values are generated by persistence.
    pub(crate) generated: Vec<FieldName>,
    /// The span of the complete attribute item.
    pub(crate) span: Span,
}
