// =============================================================================
//    Copyright (c) 2025 - 2026 Haixing Hu.
//
//    SPDX-License-Identifier: Apache-2.0
//
//    Licensed under the Apache License, Version 2.0.
// =============================================================================

/// A field participating in a primary key.
#[derive(Clone, Copy, Debug)]
pub struct PrimaryKeyFieldMetadata {
    /// The normalized field name.
    name: &'static str,
    /// Whether the persistence boundary generates this field.
    generated: bool,
}

impl PrimaryKeyFieldMetadata {
    /// Creates primary-key field metadata for a normalized field name.
    ///
    /// # Parameters
    ///
    /// * `name` - The normalized field name.
    /// * `generated` - Whether the persistence boundary generates the field.
    ///
    /// # Returns
    ///
    /// Primary-key field metadata containing the supplied name and generation
    /// policy.
    #[must_use]
    #[inline(always)]
    pub const fn new(name: &'static str, generated: bool) -> Self {
        Self { name, generated }
    }

    /// Returns the normalized field name.
    ///
    /// # Returns
    ///
    /// The normalized field name.
    #[must_use]
    #[inline(always)]
    pub const fn name(self) -> &'static str {
        self.name
    }

    /// Returns whether this key field is generated by its persistence boundary.
    ///
    /// # Returns
    ///
    /// `true` when the persistence boundary generates this field; otherwise,
    /// `false`.
    #[must_use]
    #[inline(always)]
    pub const fn is_generated(self) -> bool {
        self.generated
    }
}
