[package]
name = "qubit-model-metadata"
version = "0.1.0"
edition = "2024"
rust-version = "1.94"
authors = ["Haixing Hu <starfish.hu@gmail.com>"]
license = "Apache-2.0"
repository = "https://github.com/qubit-ltd/rs-model-metadata"
description = "Static, strongly typed metadata for Rust domain models"
homepage = "https://github.com/qubit-ltd/rs-model-metadata"
documentation = "https://docs.rs/qubit-model-metadata"
readme = "README.md"
keywords = ["metadata", "model", "reflection", "qubit", "rust"]
categories = ["data-structures", "development-tools"]
include = [
    "/Cargo.toml",
    "/LICENSE",
    "/README.md",
    "/README.zh_CN.md",
    "/src/**",
    "/doc/**",
    "/tests/**",
]

[lib]
name = "qubit_model_metadata"
doctest = true

[features]
chrono = ["dep:chrono"]
big-decimal = ["dep:bigdecimal"]
id = ["dep:qubit-id"]
datatype = ["dep:qubit-datatype"]

[dependencies]
bitflags = "2.10.0"
chrono = { version = "0.4", features = ["std"], default-features = false, optional = true }
bigdecimal = { version = "0.4", optional = true }
linkme = "0.3"
thiserror = "2"
qubit-id = { version = "0.4", optional = true }
qubit-datatype = { version = "0.11.0", path = "../../rust-common/rs-datatype", optional = true }

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(coverage)'] }
