// =============================================================================
//    Copyright (c) 2025 - 2026 Haixing Hu.
//
//    SPDX-License-Identifier: Apache-2.0
// =============================================================================

//! End-to-end runtime metadata generated by the five role macros.

use model_runtime::__private::qubit_id::Id;
use model_runtime::__private::qubit_redact::Redactor;
use model_runtime::CodecReference;
use model_runtime::IndexingReasons;
use model_runtime::ModelDescriptorExt;
use model_runtime::ModelRegistry;
use model_runtime::ModelResolver;
use model_runtime::ModelRole;
use model_runtime::PropertyPath;
use model_runtime::ResolveInputs;
use model_runtime::SerdeBehaviorSource;
use model_runtime::TypeDescriptor;
use model_runtime::TypeMetadata;
use model_runtime::expression::TypeExpression;
use qubit_codec::ValueCodecRegistry;
use qubit_codec::ValueDecoder;
use qubit_codec::ValueEncoder;
use qubit_codec::register_value_codec;
use qubit_model_derive::Entity;
use qubit_model_derive::Enum;
use qubit_model_derive::Model;
use qubit_model_derive::Projection;
use qubit_model_derive::Value;
use qubit_validator::ValidationContext;
use qubit_validator::Validator;
use qubit_validator::ValidatorRegistry;
use qubit_validator::register_validator;

#[derive(Default)]
struct EmailCodec;

#[derive(Default)]
struct EmailCanonicalCodec;

#[derive(Default)]
struct AcceptString;

impl Validator<String> for AcceptString {
    type Error = core::convert::Infallible;

    fn validate(&mut self, _value: &String, _context: &ValidationContext<'_>) -> Result<(), Self::Error> {
        Ok(())
    }
}

register_validator!(id = "runtime.email", validator = AcceptString, value = String);
register_validator!(id = "runtime.tag", validator = AcceptString, value = String);
register_validator!(id = "runtime.map_value", validator = AcceptString, value = String);
register_value_codec!(id = "runtime.alias_codec", codec = EmailCodec, value = String);

impl ValueEncoder<String> for EmailCodec {
    type Output = String;
    type Error = core::convert::Infallible;

    fn encode(&mut self, input: &String) -> Result<Self::Output, Self::Error> {
        Ok(input.clone())
    }
}

impl ValueDecoder<str> for EmailCodec {
    type Output = String;
    type Error = core::convert::Infallible;

    fn decode(&mut self, input: &str) -> Result<Self::Output, Self::Error> {
        Ok(input.to_owned())
    }
}

#[Entity(id = "runtime.Account")]
struct Account {
    #[identifier]
    id: Id,
    #[unique(respect_to(id), ignore_case = false)]
    #[validator(id = "runtime.email", depends_on(id), params(strict = true, regions = ["44", "45"]))]
    #[codec(EmailCodec)]
    #[redact(level = "medium")]
    #[serde(rename = "mail")]
    email: String,
    aliases: Vec<String>,
    #[keep_serializing]
    kept_aliases: Vec<String>,
    #[codec(id = "runtime.alias_codec")]
    nickname: Option<String>,
    #[reference(entity = Account, property = id, existing = true)]
    owner_id: Id,
}

#[Projection(id = "runtime.AccountView", source = Account)]
struct AccountView {
    #[identifier]
    id: Id,
}

#[Model(id = "runtime.Payload", no_hash)]
struct Payload {
    #[text(min_chars = 1, max_chars = 8, allowed_chars = code)]
    value: String,
    #[sequence(min_items = 1, max_items = 4, unique_items)]
    #[element(text(max_chars = 8), validator(id = "runtime.tag"), redact(level = "low"))]
    tags: Vec<String>,
    #[map(min_entries = 1, max_entries = 3)]
    #[map_key(text(max_chars = 8), redact(level = "high"))]
    #[map_value(validator(id = "runtime.map_value"), redact(level = "high"))]
    labels: std::collections::HashMap<String, String>,
}

#[Enum(id = "runtime.Status")]
enum Status {
    #[variant(name = "APPROVED")]
    Ready,
    Failed {
        message: String,
    },
}

#[Enum(id = "runtime.GenericStatus")]
enum GenericStatus<T> {
    Failed {
        #[text(max_chars = 8)]
        message: String,
    },
    Value(T),
}

#[Value(id = "runtime.Email", transparent, codec = EmailCanonicalCodec)]
struct Email(String);

impl ValueEncoder<Email> for EmailCanonicalCodec {
    type Output = String;
    type Error = core::convert::Infallible;

    fn encode(&mut self, input: &Email) -> Result<Self::Output, Self::Error> {
        Ok(input.0.clone())
    }
}

impl ValueDecoder<str> for EmailCanonicalCodec {
    type Output = Email;
    type Error = core::convert::Infallible;

    fn decode(&mut self, input: &str) -> Result<Self::Output, Self::Error> {
        Ok(Email(input.to_owned()))
    }
}

#[Model(id = "runtime.Page")]
struct Page<T> {
    value: T,
}

#[Model(id = "runtime.Buffer", no_serialize, no_deserialize)]
struct Buffer<const N: usize> {
    bytes: [u8; N],
}

#[Value(id = "runtime.Coordinate")]
struct Coordinate {
    x: i32,
    y: i32,
}

#[Value(transparent)]
struct Handle {
    value: String,
}

#[Value(transparent)]
struct SecretValue(#[redact(level = "high")] String);

#[Model(no_redact)]
struct Plain {
    value: String,
}

#[test]
fn test_role_macros_generate_metadata_capability_and_registration() {
    let cases = [
        (TypeMetadata::of::<Account>(), ModelRole::Entity, "runtime.Account"),
        (
            TypeMetadata::of::<AccountView>(),
            ModelRole::Projection,
            "runtime.AccountView",
        ),
        (TypeMetadata::of::<Payload>(), ModelRole::Model, "runtime.Payload"),
        (TypeMetadata::of::<Status>(), ModelRole::Enum, "runtime.Status"),
        (TypeMetadata::of::<Email>(), ModelRole::Value, "runtime.Email"),
    ];

    let registry = ModelRegistry::try_global().expect("generated registrations");
    for (metadata, role, id) in cases {
        assert_eq!(metadata.role(), role);
        assert_eq!(metadata.model_id().map(|value| value.as_str()), Some(id));
        assert!(std::ptr::eq(
            metadata,
            metadata.descriptor().model_metadata().expect("model capability"),
        ));
        assert!(std::ptr::eq(
            registry.metadata(id).expect("registry metadata"),
            metadata
        ));
    }
}

#[test]
fn test_field_occurrences_preserve_validator_order_and_declared_codec_id() {
    let metadata = TypeMetadata::of::<Account>();
    let id = metadata.field("id").expect("id field");
    let email = metadata.field("email").expect("email field");

    assert!(id.is_identifier());
    assert!(id.is_indexed());
    assert!(email.is_indexed());
    assert_eq!(email.validators().len(), 1);
    assert_eq!(email.validators()[0].declared_id(), "runtime.email");
    assert!(matches!(
        email.codec().map(|metadata| metadata.codec()),
        Some(CodecReference::RustType(_)),
    ));
    assert!(email.is_unique());
    assert!(email.reference().is_none());
    assert_eq!(email.validators()[0].depends_on()[0].segments(), &["id"]);
    assert_eq!(email.validators()[0].params().len(), 2);
    assert_eq!(email.serde().serialize_name(), Some("mail"));
    assert!(email.redact().is_some());
    let owner = metadata.field("owner_id").unwrap();
    assert!(owner.reference().is_some());
    assert!(owner.indexing_reasons().contains(IndexingReasons::REFERENCE));
    assert!(metadata.field("aliases").unwrap().serde().default());
    assert_eq!(
        metadata.field("aliases").unwrap().serde().default_source(),
        SerdeBehaviorSource::ModelDefault
    );
    assert_eq!(
        metadata.field("aliases").unwrap().serde().omit_source(),
        SerdeBehaviorSource::ModelDefault
    );
    assert_eq!(
        metadata.field("kept_aliases").unwrap().serde().omit_source(),
        SerdeBehaviorSource::Suppressed
    );
    assert!(metadata.field("nickname").unwrap().serde().default());
    assert!(matches!(
        metadata.field("nickname").unwrap().codec().map(|value| value.codec()),
        Some(CodecReference::DeclaredId("runtime.alias_codec")),
    ));
}

#[test]
fn test_enum_and_value_role_payloads_use_reflection_overlays() {
    let enum_metadata = TypeMetadata::of::<Status>().as_enum().expect("enum role");
    assert!(TypeMetadata::of::<Status>().fields().is_empty());
    assert_eq!(
        enum_metadata.variant_by_rust_name("Ready").unwrap().canonical_name(),
        "APPROVED"
    );
    assert_eq!(enum_metadata.variant_by_rust_name("Failed").unwrap().fields().len(), 1);
    assert_eq!(serde_json::to_string(&Status::Ready).unwrap(), r#""READY""#);
    assert_eq!(
        serde_json::to_string(&Status::Failed { message: "x".into() }).unwrap(),
        r#"{"FAILED":{"message":"x"}}"#,
    );

    let value = TypeMetadata::of::<Email>().as_value().expect("value role");
    assert!(value.is_transparent());
    assert_eq!(value.transparent_field().unwrap().index(), 0);
    let email = Email("a@example.com".into());
    assert_eq!(email.to_string(), "a@example.com");
    assert!(format!("{email:?}").starts_with("Email("));
    assert_eq!(serde_json::to_string(&email).unwrap(), r#""a@example.com""#);
    let redacted = Redactor::application_default().redact(&email);
    assert_eq!(redacted.text().as_str(), "\"a@example.com\"");
    let restored: Email = serde_json::from_str(r#""restored@example.com""#).unwrap();
    assert_eq!(restored.0, "restored@example.com");
    let handle = Handle {
        value: "alice".to_owned(),
    };
    assert_eq!(handle.to_string(), "alice");
    assert_eq!(serde_json::to_string(&handle).unwrap(), r#""alice""#);
    let restored: Handle = serde_json::from_str(r#""bob""#).unwrap();
    assert_eq!(restored.value, "bob");
    let secret = SecretValue("raw-secret".to_owned());
    let redacted = Redactor::application_default().redact(&secret);
    assert!(!redacted.text().as_str().contains("raw-secret"));
    assert!(format!("{secret:?}").starts_with("SecretValue("));
    assert!(!format!("{secret:?}").contains("raw-secret"));
    assert!(!secret.to_string().contains("raw-secret"));
    assert!(!TypeMetadata::of::<Coordinate>().as_value().unwrap().is_transparent());
    let account = Account {
        id: Id::new(1),
        email: "a@example.com".into(),
        aliases: Vec::new(),
        kept_aliases: Vec::new(),
        nickname: None,
        owner_id: Id::new(1),
    };
    let serialized = serde_json::to_string(&account).unwrap();
    assert_eq!(
        serialized,
        r#"{"id":"1","mail":"*******m","kept_aliases":[],"owner_id":"1"}"#
    );
    assert!(!format!("{account:?}").contains("a@example.com"));
    assert!(!format!("{account}").contains("a@example.com"));
    let _ = AccountView { id: Id::new(1) };
    let payload = Payload {
        value: "visible".into(),
        tags: vec!["tag-secret".into()],
        labels: [("key".to_owned(), "map-secret".to_owned())].into(),
    };
    let serialized = serde_json::to_string(&payload).unwrap();
    assert!(!serialized.contains("key"));
    assert!(!serialized.contains("tag-secret"));
    assert!(!serialized.contains("map-secret"));
    let redacted = Redactor::application_default().redact(&payload);
    assert!(!redacted.text().as_str().contains("key"));
    let _ = Status::Ready;
    let Status::Failed { message } = (Status::Failed { message: "x".into() }) else {
        unreachable!()
    };
    assert_eq!(message, "x");
    let _ = Email("a@example.com".into()).0;
    assert_eq!(TypeDescriptor::of::<Account>().fields().len(), 6);
}

#[test]
fn test_redacted_map_key_collisions_fail_serialization() {
    let payload = Payload {
        value: "visible".into(),
        tags: vec!["tag".into()],
        labels: [
            ("first".to_owned(), "one".to_owned()),
            ("second".to_owned(), "two".to_owned()),
        ]
        .into(),
    };
    let error = serde_json::to_string(&payload).expect_err("fixed masks collide");
    assert!(error.to_string().contains("redacted map keys collide"));
}

#[test]
fn test_no_redact_uses_plain_default_interfaces() {
    let plain = Plain {
        value: "visible".to_owned(),
    };
    assert_eq!(format!("{plain:?}"), "Plain { value: \"visible\" }");
    assert_eq!(plain.to_string(), "Plain { value: \"visible\" }");
    assert_eq!(serde_json::to_string(&plain).unwrap(), r#"{"value":"visible"}"#);
}

#[test]
fn test_constraints_and_selectors_are_normalized() {
    let metadata = TypeMetadata::of::<Payload>();
    assert_eq!(
        metadata.field("value").unwrap().text_constraint().unwrap().max_chars(),
        Some(8)
    );
    let sequence = metadata.field("tags").unwrap().sequence_constraint().unwrap();
    assert_eq!(sequence.min_items(), Some(1));
    assert!(sequence.unique_items());
    let element = sequence.element().expect("element selector");
    assert_eq!(element.constraints().len(), 1);
    assert_eq!(element.validators()[0].declared_id(), "runtime.tag");
    assert!(element.redact().is_some());
    let map = metadata.field("labels").unwrap().map_constraint().unwrap();
    assert!(map.key().is_some());
    assert_eq!(map.value().unwrap().validators()[0].declared_id(), "runtime.map_value");
}

#[test]
fn test_generic_model_registers_only_its_definition() {
    let concrete = TypeMetadata::of::<Page<u64>>();
    assert_eq!(concrete.model_id(), None);
    assert!(concrete.descriptor().model_metadata().is_some());
    let definition = concrete.generic_definition().expect("generic definition");
    assert_eq!(definition.model_id().as_str(), "runtime.Page");
    assert_eq!(definition.definition().parameters().len(), 1);
    assert_eq!(definition.fields().len(), 1);
    let template_field = &definition.fields()[0];
    assert_eq!(template_field.name(), Some("value"));
    assert!(template_field.descriptor().is_none());
    assert!(matches!(
        template_field.type_ref().as_symbolic(),
        Some(TypeExpression::Parameter(name)) if name.as_ref() == "T",
    ));
    let registry = ModelRegistry::try_global().expect("generic registration");
    assert!(std::ptr::eq(registry.generic("runtime.Page").unwrap(), definition));
    assert!(registry.metadata("runtime.Page").is_none());

    let buffer = TypeMetadata::of::<Buffer<4>>();
    let definition = buffer.generic_definition().expect("const generic definition");
    assert_eq!(definition.definition().parameters().len(), 1);
    assert!(definition.fields()[0].type_ref().as_symbolic().is_some());
}

#[test]
fn test_generic_enum_registration_preserves_variant_field_overlays() {
    let _ = GenericStatus::<u8>::Value(1);
    let registry = ModelRegistry::try_global().expect("valid model registry");
    let metadata = registry
        .generic("runtime.GenericStatus")
        .expect("registered generic enum");

    assert!(metadata.fields().is_empty());
    let variants = metadata.variants();
    assert_eq!(variants.len(), 2);
    assert_eq!(variants[0].rust_name(), "Failed");
    assert_eq!(variants[0].fields().len(), 1);
    assert_eq!(
        variants[0].fields()[0]
            .text_constraint()
            .and_then(|constraint| constraint.max_chars()),
        Some(8),
    );
}

#[test]
fn test_resolver_builds_scoped_unique_and_reference_queries() {
    let registry = ModelRegistry::try_global().expect("generated registrations");
    let graph = ModelResolver::new(ResolveInputs {
        models: registry,
        validators: ValidatorRegistry::global(),
        codecs: ValueCodecRegistry::global(),
    })
    .resolve_all()
    .expect("valid generated model graph");
    let entity = TypeMetadata::of::<Account>().as_entity().unwrap();
    let query = graph.query(entity).expect("entity query");

    assert!(query.filter(&PropertyPath::new(&["email"])).is_some());
    assert!(query.filter(&PropertyPath::new(&["owner_id"])).is_some());
    assert_eq!(
        query.filter_by_flat_name("owner_id").unwrap().path().segments(),
        &["owner_id"]
    );
    assert!(query.unique_keys().iter().any(|key| {
        key.paths().map(|path| path.to_string()).collect::<Vec<_>>() == vec!["email".to_owned(), "id".to_owned()]
    }));
}
