// =============================================================================
//    Copyright (c) 2025 - 2026 Haixing Hu.
//
//    SPDX-License-Identifier: Apache-2.0
//
//    Licensed under the Apache License, Version 2.0.
// =============================================================================

//! Integration tests for runtime metadata generated by the `Model` attribute.

use std::collections::BTreeMap;
use std::collections::BTreeSet;
use std::collections::BinaryHeap;
use std::collections::HashMap;
use std::collections::HashSet;
use std::collections::LinkedList;
use std::collections::VecDeque;

use model_runtime::AllowedChars;
use model_runtime::AttributeKind;
use model_runtime::AttributeMetadata;
use model_runtime::AttributeQuery;
use model_runtime::DecimalSemantic;
use model_runtime::EnumVariantKind;
use model_runtime::FieldPath;
use model_runtime::HasModelRegistration;
use model_runtime::HasTypeShape;
use model_runtime::ModelRegistry;
use model_runtime::ReferencePathSegment;
use model_runtime::ReferenceTarget;
use model_runtime::RoundingMode;
use model_runtime::TemporalPrecision;
use model_runtime::TextFormat;
use model_runtime::TypeCapabilities;
use model_runtime::TypeKind;
use model_runtime::TypeShape;
use model_runtime::UniqueComparison;
use model_runtime::metadata_of;
use qubit_model_derive::Enum;
use qubit_model_derive::Model;

#[allow(dead_code)]
#[Model(id = "test.derive.User")]
struct User {
    #[identifier(generated)]
    id: Option<i64>,
    #[unique]
    nickname: Option<String>,
}

#[allow(dead_code)]
#[Model(id = "test.derive.ScopedUnique")]
struct ScopedUnique {
    organization_id: i64,
    #[unique(respectTo = [organization_id])]
    code: String,
}

#[allow(dead_code)]
#[Model(id = "test.derive.NumericUnique")]
struct NumericUnique {
    #[unique]
    value: i64,
}

#[Model(id = "test.derive.Empty")]
struct Empty;

#[Model(id = "test.derive.UserId")]
#[allow(dead_code)]
struct UserId(i64);

#[Model(id = "test.derive.DisplayName")]
#[allow(dead_code)]
struct DisplayName(String);

#[Model(id = "test.derive.Phone", textual)]
#[allow(dead_code)]
struct Phone {
    country_area: Option<String>,
    city_area: Option<String>,
    number: String,
}

#[Model(id = "test.derive.PhoneLoginParams")]
#[allow(dead_code)]
struct PhoneLoginParams {
    #[text(format = mobile)]
    mobile: Option<Phone>,
}

#[Enum(id = "test.derive.Status")]
#[allow(dead_code)]
enum Status {
    Draft,
    Published,
}

#[Enum(id = "test.derive.SerializedStatus")]
enum SerializedStatus {
    #[serde(rename = "reviewing")]
    Reviewing,
    #[serde(rename(serialize = "invalid-state"))]
    Invalid,
}

#[Enum(id = "test.derive.SerdeDecoratedStatus")]
enum SerdeDecoratedStatus {
    #[serde(rename(serialize = "OUT", deserialize = "IN"), alias = "OLD")]
    Value,
}

#[allow(non_camel_case_types)]
#[Enum(id = "test.derive.SerdeNamingEdgeCases")]
enum SerdeNamingEdgeCases {
    r#type,
    HTTPServer,
    XMLHttpRequest,
    IPv6Address,
    A1B2,
    JSON2XML,
    Éclair,
}

#[Enum(id = "test.derive.Event")]
enum Event {
    Started,
    Progress(u8, String),
    Optional(Option<String>, Vec<String>),
    OptionalValues(Option<String>, Option<String>),
    Failed {
        #[text(max_chars = 200)]
        #[serde(rename = "error_message")]
        message: String,
        details: Option<String>,
        tags: Vec<String>,
    },
}

#[Enum(
    id = "test.derive.PayloadSerdeDefaults",
    no_debug,
    no_display,
    no_partial_eq,
    no_hash
)]
enum PayloadSerdeDefaults {
    SingleOption(Option<String>),
    SingleVec(Vec<String>),
    OptionTail(u8, Option<String>),
    KeptOption(u8, #[keep_serializing] Option<String>),
    VecTail(u8, Vec<String>),
    LinkedListTail(u8, LinkedList<String>),
    VecDequeTail(u8, VecDeque<String>),
    HashMapTail(u8, HashMap<String, String>),
    BTreeMapTail(u8, BTreeMap<String, String>),
    HashSetTail(u8, HashSet<String>),
    BTreeSetTail(u8, BTreeSet<String>),
    BinaryHeapTail(u8, BinaryHeap<String>),
    ArrayTail(u8, [String; 0]),
}

#[allow(dead_code)]
#[Enum(
    id = "test.derive.PayloadMetadata",
    no_clone,
    no_debug,
    no_display,
    no_partial_eq,
    no_hash,
    no_serialize,
    no_deserialize
)]
enum PayloadMetadata {
    Tuple(
        #[text(max_chars = 8)] String,
        #[sequence(min_items = 1, max_items = 3, unique_items)] Vec<String>,
        #[map(min_entries = 1, max_entries = 2)] HashMap<String, String>,
    ),
    Struct {
        #[time(precision = millisecond)]
        created_at: chrono::DateTime<chrono::Utc>,
        #[decimal(precision = 8, scale = 3, rounding = half_up)]
        ratio: bigdecimal::BigDecimal,
        #[money(precision = 12, scale = 2, rounding = half_even)]
        balance: bigdecimal::BigDecimal,
        #[element(text(allowed_chars = ascii))]
        codes: Vec<String>,
        #[codec = "encrypted"]
        #[generator(name = "token")]
        value: String,
        #[opaque]
        external: ExternalValue,
    },
}

#[allow(dead_code)]
#[Model(id = "test.derive.Organization")]
struct Organization {
    id: i64,
}

struct ExternalValue;

#[allow(dead_code)]
#[Model(id = "test.derive.OpaqueContainer")]
struct OpaqueContainer {
    #[opaque]
    external_values: Option<Vec<i128>>,
}

#[allow(dead_code)]
#[Model(
    id = "test.derive.AttributedModel",
    no_clone,
    no_debug,
    no_display,
    no_eq,
    no_partial_eq,
    no_hash,
    no_serialize,
    no_deserialize,
    primary_key(fields(id), generated(id)),
    index(name = "created_at_index", fields(created_at)),
    key(name = "account", fields(organization_id, username)),
    ownership(owner = Organization)
)]
struct AttributedModel {
    id: i64,
    #[reference(
        entity = "test.derive.Organization",
        property = id,
        existing = true,
        path = "organization.id"
    )]
    organization_id: i64,
    #[reference(entity = "test.derive.Organization")]
    organization: Organization,
    #[lookup_relation(target = Organization, target_field = id)]
    organization_lookup: i64,
    #[text(
        min_chars = 3,
        max_chars = 32,
        min_bytes = 3,
        max_bytes = 64,
        allowed_chars = ascii,
        non_blank,
        format = email
    )]
    #[unique(
        name = "organization_username",
        respectTo = [organization_id],
        ignoreCase = true
    )]
    username: String,
    #[sequence(min_items = 1, max_items = 5, unique_items)]
    aliases: Vec<String>,
    #[element(text(allowed_chars = ascii))]
    ascii_codes: [String; 2],
    #[map(min_entries = 1, max_entries = 4)]
    labels: HashMap<String, String>,
    #[time(precision = millisecond)]
    created_at: chrono::DateTime<chrono::Utc>,
    #[decimal(precision = 8, scale = 3, rounding = half_up)]
    ratio: bigdecimal::BigDecimal,
    #[money(precision = 12, scale = 2, rounding = half_even)]
    balance: bigdecimal::BigDecimal,
    #[element(decimal(scale = 2))]
    decimal_values: Vec<bigdecimal::BigDecimal>,
    #[text(format = mobile)]
    mobile: String,
    #[codec = "encrypted"]
    #[generator(name = "account_balance")]
    secret: String,
    verification_code: String,
    #[opaque]
    external: ExternalValue,
}

/// Verifies that the derive macro preserves the declared stable model ID.
#[test]
fn test_derive_emits_declared_model_id() {
    assert_eq!(metadata_of::<User>().id().as_str(), "test.derive.User");
}

#[test]
fn test_derive_emits_declared_fields_and_nullable_shape() {
    let metadata = metadata_of::<User>();

    assert_eq!(metadata.fields().count(), 2);
    assert!(metadata.field("nickname").expect("nickname metadata").is_nullable());
}

#[test]
fn test_derive_preserves_opaque_container_shape() {
    let field = metadata_of::<OpaqueContainer>()
        .field("external_values")
        .expect("opaque container field metadata");

    assert!(field.is_nullable());
    assert!(matches!(
        field.field_type().shape(),
        TypeShape::Optional(inner)
            if matches!(inner.shape(), TypeShape::Sequence(element)
                if matches!(element.shape(), TypeShape::Opaque))
    ));
}

#[test]
fn test_shorthand_normalizes_to_type_constraints() {
    let metadata = metadata_of::<User>();

    let primary_key = metadata.primary_key().expect("primary key");
    assert_eq!(
        primary_key
            .fields()
            .iter()
            .map(|field| field.name())
            .collect::<Vec<_>>(),
        ["id"]
    );
    assert!(primary_key.fields()[0].is_generated());

    let unique = metadata.unique_constraints().next().expect("unique metadata");
    assert_eq!(
        unique
            .fields()
            .iter()
            .map(|field| (field.name(), field.comparison()))
            .collect::<Vec<_>>(),
        [("nickname", UniqueComparison::IgnoreCase)]
    );

    assert_eq!(metadata.indexes().count(), 0);
}

#[test]
fn test_field_unique_respect_to_expands_as_ordered_composite_constraint() {
    let unique = metadata_of::<ScopedUnique>()
        .unique_constraints()
        .next()
        .expect("scoped unique metadata");
    assert_eq!(
        unique
            .fields()
            .iter()
            .map(|field| (field.name(), field.comparison()))
            .collect::<Vec<_>>(),
        [
            ("organization_id", UniqueComparison::Exact),
            ("code", UniqueComparison::IgnoreCase),
        ]
    );
}

#[test]
fn test_non_text_field_unique_defaults_to_exact_comparison() {
    let unique = metadata_of::<NumericUnique>()
        .unique_constraints()
        .next()
        .expect("numeric unique metadata");
    assert_eq!(unique.comparison_of("value"), Some(UniqueComparison::Exact));
}

#[test]
fn test_derive_emits_empty_struct_metadata() {
    let metadata = metadata_of::<Empty>();

    assert!(matches!(metadata.kind(), TypeKind::Struct(_)));
    assert_eq!(metadata.fields().count(), 0);
}

#[test]
fn test_derive_emits_newtype_metadata() {
    let metadata = metadata_of::<UserId>();

    assert!(matches!(metadata.kind(), TypeKind::Newtype(newtype)
        if newtype.field().ordinal() == 0
            && newtype.field().name() == "0"
            && newtype.field().rust_type_name() == "i64"));
}

#[test]
fn test_derive_newtype_inherits_inner_type_capabilities() {
    assert_eq!(<DisplayName as HasTypeShape>::CAPABILITIES, TypeCapabilities::TEXT);
}

#[test]
fn test_textual_named_model_accepts_mobile_constraints() {
    assert_eq!(<Phone as HasTypeShape>::CAPABILITIES, TypeCapabilities::TEXT);
    assert!(matches!(
        metadata_of::<PhoneLoginParams>()
            .field("mobile")
            .expect("mobile field metadata")
            .text_constraint(),
        Some(constraint) if constraint.format() == Some(TextFormat::Mobile)
    ));
}

#[test]
fn test_derive_emits_fieldless_enum_metadata() {
    let metadata = metadata_of::<Status>();

    assert!(matches!(metadata.kind(), TypeKind::Enum(enum_metadata)
        if enum_metadata.variants().len() == 2
            && enum_metadata.variants()[0].name() == "DRAFT"
            && enum_metadata.variants()[1].ordinal() == 1));
}

#[test]
fn test_derive_emits_data_enum_variant_metadata() {
    let TypeKind::Enum(metadata) = metadata_of::<Event>().kind() else {
        panic!("Event should have enum metadata");
    };
    let variants = metadata.variants();

    assert!(matches!(variants[0].kind(), EnumVariantKind::Unit));
    assert!(matches!(variants[1].kind(), EnumVariantKind::Tuple(_)));
    assert_eq!(variants[1].fields().len(), 2);
    assert_eq!(variants[1].fields()[0].name(), "0");
    assert_eq!(variants[1].fields()[1].name(), "1");
    assert!(matches!(variants[2].kind(), EnumVariantKind::Tuple(_)));
    assert!(matches!(variants[3].kind(), EnumVariantKind::Tuple(_)));
    assert!(matches!(variants[4].kind(), EnumVariantKind::Struct(_)));
    let message = variants[4].fields()[0];
    assert_eq!(message.name(), "message");
    assert_eq!(message.text_constraint().and_then(|text| text.max_chars()), Some(200));
}

#[test]
fn test_data_enum_generates_names_display_and_serde_defaults() {
    let progress = Event::Progress(42, "items".to_owned());
    let failed = Event::Failed {
        message: "timeout".to_owned(),
        details: None,
        tags: Vec::new(),
    };

    assert_eq!(progress.name(), "PROGRESS");
    assert_eq!(progress.to_string(), "PROGRESS(42, \"items\")");
    assert_eq!(
        failed.to_string(),
        "FAILED { message: \"timeout\", details: None, tags: [] }"
    );
    assert_eq!(
        serde_json::to_string(&failed).expect("data enum should serialize"),
        r#"{"FAILED":{"error_message":"timeout"}}"#
    );
}

#[test]
fn test_data_enum_preserves_non_trailing_tuple_field_positions() {
    let required_tail = Event::Optional(None, vec!["tag".to_owned()]);
    let optional_tail = Event::OptionalValues(None, Some("tail".to_owned()));

    assert_eq!(
        serde_json::to_string(&required_tail).expect("tuple data enum should serialize"),
        r#"{"OPTIONAL":[null,["tag"]]}"#
    );
    assert_eq!(
        serde_json::to_string(&optional_tail).expect("tuple data enum should serialize"),
        r#"{"OPTIONAL_VALUES":[null,"tail"]}"#
    );
    assert_eq!(
        serde_json::from_str::<Event>(r#"{"OPTIONAL_VALUES":[null,"tail"]}"#)
            .expect("tuple data enum should deserialize"),
        optional_tail
    );
}

#[test]
fn test_data_enum_omits_trailing_tuple_fields_with_defaults() {
    let optional = Event::Optional(None, Vec::new());
    let serialized = serde_json::to_string(&optional).expect("tuple data enum should serialize");

    assert_eq!(serialized, r#"{"OPTIONAL":[null]}"#);
    assert_eq!(
        serde_json::from_str::<Event>(&serialized).expect("tuple data enum should deserialize"),
        optional,
    );
}

/// Verifies Serde preserves a single newtype payload even when it is empty.
#[test]
fn test_data_enum_preserves_single_payload_values() {
    let optional = PayloadSerdeDefaults::SingleOption(None);
    let values = PayloadSerdeDefaults::SingleVec(Vec::new());

    assert_eq!(
        serde_json::to_string(&optional).expect("single option payload should serialize"),
        r#"{"SINGLE_OPTION":null}"#,
    );
    assert_eq!(
        serde_json::to_string(&values).expect("single vector payload should serialize"),
        r#"{"SINGLE_VEC":[]}"#,
    );
    assert_eq!(
        serde_json::from_str::<PayloadSerdeDefaults>(r#"{"SINGLE_OPTION":null}"#)
            .expect("single option payload should deserialize")
            .name(),
        "SINGLE_OPTION",
    );
    assert_eq!(
        serde_json::from_str::<PayloadSerdeDefaults>(r#"{"SINGLE_VEC":[]}"#)
            .expect("single vector payload should deserialize")
            .name(),
        "SINGLE_VEC",
    );
}

/// Verifies every supported empty tuple payload receives the same Serde
/// omission and defaulting behavior as a struct field.
#[test]
fn test_data_enum_omits_and_restores_trailing_payload_defaults() {
    let cases = [
        (
            PayloadSerdeDefaults::OptionTail(7, None),
            r#"{"OPTION_TAIL":[7]}"#,
            "OPTION_TAIL",
        ),
        (
            PayloadSerdeDefaults::VecTail(7, Vec::new()),
            r#"{"VEC_TAIL":[7]}"#,
            "VEC_TAIL",
        ),
        (
            PayloadSerdeDefaults::LinkedListTail(7, LinkedList::new()),
            r#"{"LINKED_LIST_TAIL":[7]}"#,
            "LINKED_LIST_TAIL",
        ),
        (
            PayloadSerdeDefaults::VecDequeTail(7, VecDeque::new()),
            r#"{"VEC_DEQUE_TAIL":[7]}"#,
            "VEC_DEQUE_TAIL",
        ),
        (
            PayloadSerdeDefaults::HashMapTail(7, HashMap::new()),
            r#"{"HASH_MAP_TAIL":[7]}"#,
            "HASH_MAP_TAIL",
        ),
        (
            PayloadSerdeDefaults::BTreeMapTail(7, BTreeMap::new()),
            r#"{"B_TREE_MAP_TAIL":[7]}"#,
            "B_TREE_MAP_TAIL",
        ),
        (
            PayloadSerdeDefaults::HashSetTail(7, HashSet::new()),
            r#"{"HASH_SET_TAIL":[7]}"#,
            "HASH_SET_TAIL",
        ),
        (
            PayloadSerdeDefaults::BTreeSetTail(7, BTreeSet::new()),
            r#"{"B_TREE_SET_TAIL":[7]}"#,
            "B_TREE_SET_TAIL",
        ),
        (
            PayloadSerdeDefaults::BinaryHeapTail(7, BinaryHeap::new()),
            r#"{"BINARY_HEAP_TAIL":[7]}"#,
            "BINARY_HEAP_TAIL",
        ),
        (
            PayloadSerdeDefaults::ArrayTail(7, []),
            r#"{"ARRAY_TAIL":[7]}"#,
            "ARRAY_TAIL",
        ),
    ];

    for (value, expected, name) in cases {
        let serialized = serde_json::to_string(&value).expect("empty tuple payload should serialize");
        assert_eq!(serialized, expected);
        let restored: PayloadSerdeDefaults =
            serde_json::from_str(&serialized).expect("omitted tuple payload should deserialize");
        assert_eq!(restored.name(), name);
        assert_eq!(
            serde_json::to_string(&restored).expect("restored tuple payload should serialize"),
            expected
        );
    }
}

/// Verifies `keep_serializing` leaves an otherwise empty tuple payload on the
/// wire and does not add implicit deserialization defaults.
#[test]
fn test_data_enum_keep_serializing_preserves_trailing_option() {
    let serialized = serde_json::to_string(&PayloadSerdeDefaults::KeptOption(7, None))
        .expect("kept optional payload should serialize");

    assert_eq!(serialized, r#"{"KEPT_OPTION":[7,null]}"#);
    assert!(serde_json::from_str::<PayloadSerdeDefaults>(r#"{"KEPT_OPTION":[7]}"#).is_err());
}

/// Verifies every allowed payload helper expands into its runtime metadata.
#[test]
fn test_data_enum_payload_attributes_expand_into_runtime_metadata() {
    let TypeKind::Enum(metadata) = metadata_of::<PayloadMetadata>().kind() else {
        panic!("PayloadMetadata should have enum metadata");
    };
    let tuple = metadata.variant("TUPLE").expect("tuple variant metadata");
    let structure = metadata.variant("STRUCT").expect("struct variant metadata");

    assert_eq!(
        tuple.fields()[0].text_constraint().and_then(|text| text.max_chars()),
        Some(8)
    );
    assert!(matches!(
        tuple.fields()[1].attribute(AttributeKind::Sequence),
        Some(AttributeMetadata::Sequence(sequence))
            if sequence.min_items() == Some(1)
                && sequence.max_items() == Some(3)
                && sequence.has_unique_items()
    ));
    assert!(matches!(
        tuple.fields()[2].attribute(AttributeKind::Map),
        Some(AttributeMetadata::Map(map))
            if map.min_entries() == Some(1) && map.max_entries() == Some(2)
    ));
    assert!(matches!(
        structure.fields()[0].attribute(AttributeKind::Temporal),
        Some(AttributeMetadata::Temporal(temporal))
            if temporal.precision() == TemporalPrecision::Millisecond
    ));
    assert!(matches!(
        structure.fields()[1].attribute(AttributeKind::Decimal),
        Some(AttributeMetadata::Decimal(decimal))
            if decimal.precision() == Some(8)
                && decimal.scale() == 3
                && decimal.rounding() == RoundingMode::HalfUp
                && decimal.semantic() == DecimalSemantic::Number
    ));
    assert!(matches!(
        structure.fields()[2].attribute(AttributeKind::Decimal),
        Some(AttributeMetadata::Decimal(decimal))
            if decimal.precision() == Some(12)
                && decimal.scale() == 2
                && decimal.rounding() == RoundingMode::HalfEven
                && decimal.semantic() == DecimalSemantic::Money
    ));
    assert!(matches!(
        structure.fields()[3].element_metadata(),
        Some(element)
            if matches!(
                element.attributes(),
                [AttributeMetadata::Text(text)] if text.allowed_chars() == AllowedChars::Ascii
            )
    ));
    assert!(matches!(
        structure.fields()[4].attribute(AttributeKind::Codec),
        Some(AttributeMetadata::Codec(codec)) if codec.name() == "encrypted"
    ));
    assert!(matches!(
        structure.fields()[4].attribute(AttributeKind::Generator),
        Some(AttributeMetadata::Generator(generator)) if generator.name() == "token"
    ));
    assert!(matches!(structure.fields()[5].field_type().shape(), TypeShape::Opaque));
    assert!(matches!(tuple.fields()[0].field_type().shape(), TypeShape::Scalar(_)));
}

#[test]
fn test_enum_name_methods_follow_serde_serialization_names() {
    assert_eq!(SerializedStatus::Reviewing.name(), "reviewing");
    assert_eq!(
        SerializedStatus::from_name("reviewing"),
        Some(SerializedStatus::Reviewing)
    );
    assert_eq!(SerializedStatus::Invalid.name(), "invalid-state");
    assert_eq!(
        SerializedStatus::from_name("invalid-state"),
        Some(SerializedStatus::Invalid)
    );
    assert_eq!(SerializedStatus::from_name("invalid"), None);
}

#[test]
fn test_enum_name_methods_ignore_noncanonical_serde_variant_names() {
    assert_eq!(SerdeDecoratedStatus::Value.name(), "OUT");
    assert_eq!(
        SerdeDecoratedStatus::from_name("OUT"),
        Some(SerdeDecoratedStatus::Value)
    );
    assert_eq!(SerdeDecoratedStatus::from_name("IN"), None);
    assert_eq!(
        serde_json::to_string(&SerdeDecoratedStatus::Value).expect("status should serialize"),
        r#""OUT""#
    );
    assert_eq!(
        serde_json::from_str::<SerdeDecoratedStatus>(r#""IN""#).expect("status should deserialize"),
        SerdeDecoratedStatus::Value
    );
    assert_eq!(
        serde_json::from_str::<SerdeDecoratedStatus>(r#""OLD""#).expect("status alias should deserialize"),
        SerdeDecoratedStatus::Value
    );
}

/// Verifies implicit canonical names exactly match Serde's variant renaming.
#[test]
fn test_enum_name_methods_match_serde_for_raw_and_acronym_variants() {
    let cases = [
        SerdeNamingEdgeCases::r#type,
        SerdeNamingEdgeCases::HTTPServer,
        SerdeNamingEdgeCases::XMLHttpRequest,
        SerdeNamingEdgeCases::IPv6Address,
        SerdeNamingEdgeCases::A1B2,
        SerdeNamingEdgeCases::JSON2XML,
        SerdeNamingEdgeCases::Éclair,
    ];

    for value in cases {
        let serialized = serde_json::to_string(&value).expect("edge-case enum should serialize");
        let serde_name: String = serde_json::from_str(&serialized).expect("enum should serialize as a JSON string");

        assert_eq!(value.name(), serde_name);
        assert_eq!(SerdeNamingEdgeCases::from_name(&serde_name), Some(value));
    }
}

#[test]
fn test_model_attributes_expand_in_canonical_form() {
    let metadata = metadata_of::<AttributedModel>();

    let primary_key = metadata.primary_key().expect("primary key metadata");
    assert_eq!(
        primary_key
            .fields()
            .iter()
            .map(|field| (field.name(), field.is_generated()))
            .collect::<Vec<_>>(),
        [("id", true)]
    );
    let unique = metadata.unique_constraints().next().expect("unique metadata");
    assert_eq!(unique.name(), Some("organization_username"));
    assert_eq!(unique.comparison_of("organization_id"), Some(UniqueComparison::Exact));
    assert_eq!(unique.comparison_of("username"), Some(UniqueComparison::IgnoreCase));
    let index = metadata
        .indexes()
        .find(|index| index.name() == Some("created_at_index"))
        .expect("created-at index metadata");
    assert_eq!(index.name(), Some("created_at_index"));
    assert_eq!(index.fields(), &["created_at"]);
    assert!(metadata.indexes().any(|index| index.fields() == ["organization_id"]));
    assert!(matches!(
        metadata.attribute(AttributeKind::Key),
        Some(AttributeMetadata::Key(key))
            if key.name() == Some("account") && key.contains("username")
    ));
    assert!(matches!(
        metadata.attribute(AttributeKind::Ownership),
        Some(AttributeMetadata::Ownership(ownership))
            if ownership.owner().identity().type_name()
                == core::any::type_name::<Organization>()
    ));
}

#[test]
fn test_text_sequence_and_map_attributes_expand() {
    let metadata = metadata_of::<AttributedModel>();
    let text = metadata
        .field("username")
        .expect("username metadata")
        .text_constraint()
        .expect("text constraint");
    assert_eq!(text.min_chars(), Some(3));
    assert_eq!(text.max_chars(), Some(32));
    assert_eq!(text.min_bytes(), Some(3));
    assert_eq!(text.max_bytes(), Some(64));
    assert_eq!(text.allowed_chars(), AllowedChars::Ascii);
    assert!(text.is_non_blank());
    assert_eq!(text.format(), Some(TextFormat::Email));

    assert!(matches!(
        metadata
            .field("aliases")
            .expect("aliases metadata")
            .attribute(AttributeKind::Sequence),
        Some(AttributeMetadata::Sequence(sequence))
            if sequence.min_items() == Some(1)
                && sequence.max_items() == Some(5)
                && sequence.has_unique_items()
    ));
    assert!(matches!(
        metadata
            .field("labels")
            .expect("labels metadata")
            .attribute(AttributeKind::Map),
        Some(AttributeMetadata::Map(map))
            if map.min_entries() == Some(1) && map.max_entries() == Some(4)
    ));
}

#[test]
fn test_temporal_decimal_and_money_attributes_expand() {
    let metadata = metadata_of::<AttributedModel>();

    assert!(matches!(
        metadata
            .field("created_at")
            .expect("created_at metadata")
            .attribute(AttributeKind::Temporal),
        Some(AttributeMetadata::Temporal(temporal))
            if temporal.precision() == TemporalPrecision::Millisecond
    ));
    assert!(matches!(
        metadata
            .field("ratio")
            .expect("ratio metadata")
            .attribute(AttributeKind::Decimal),
        Some(AttributeMetadata::Decimal(decimal))
            if decimal.precision() == Some(8)
                && decimal.scale() == 3
                && decimal.rounding() == RoundingMode::HalfUp
                && decimal.semantic() == DecimalSemantic::Number
    ));
    assert!(matches!(
        metadata
            .field("balance")
            .expect("balance metadata")
            .attribute(AttributeKind::Decimal),
        Some(AttributeMetadata::Decimal(decimal))
            if decimal.precision() == Some(12)
                && decimal.scale() == 2
                && decimal.rounding() == RoundingMode::HalfEven
                && decimal.semantic() == DecimalSemantic::Money
    ));
}

#[test]
fn test_migrated_element_and_mobile_constraints_expand() {
    let metadata = metadata_of::<AttributedModel>();
    let ascii_element = metadata
        .field("ascii_codes")
        .expect("ascii_codes metadata")
        .element_metadata()
        .expect("ASCII element metadata");
    assert!(matches!(
        ascii_element.attributes(),
        [AttributeMetadata::Text(text)]
            if text.allowed_chars() == AllowedChars::Ascii
    ));

    let decimal_element = metadata
        .field("decimal_values")
        .expect("decimal_values metadata")
        .element_metadata()
        .expect("decimal element metadata");
    assert!(matches!(
        decimal_element.attributes(),
        [AttributeMetadata::Decimal(decimal)]
            if decimal.scale() == 2
                && decimal.semantic() == DecimalSemantic::Number
    ));

    assert_eq!(
        metadata
            .field("mobile")
            .expect("mobile metadata")
            .text_constraint()
            .and_then(|text| text.format()),
        Some(TextFormat::Mobile)
    );
}

#[test]
fn test_reference_and_strategy_attributes_expand() {
    let metadata = metadata_of::<AttributedModel>();
    let reference = metadata
        .field("organization_id")
        .expect("organization_id metadata")
        .reference()
        .expect("reference metadata");
    assert_eq!(reference.entity().as_str(), "test.derive.Organization");
    assert_eq!(reference.target(), ReferenceTarget::Property(FieldPath::new(&["id"])));
    assert!(reference.existing());
    assert_eq!(
        reference.path().expect("reference path").segments(),
        &[
            ReferencePathSegment::Field("organization"),
            ReferencePathSegment::Field("id"),
        ]
    );

    let whole_reference = metadata
        .field("organization")
        .expect("organization metadata")
        .reference()
        .expect("whole model reference metadata");
    assert_eq!(whole_reference.entity().as_str(), "test.derive.Organization");
    assert_eq!(whole_reference.target(), ReferenceTarget::WholeModel);
    assert!(whole_reference.existing());
    assert_eq!(whole_reference.path(), None);

    let lookup = metadata
        .field("organization_lookup")
        .expect("organization lookup metadata")
        .lookup_relation()
        .expect("lookup relation metadata");
    assert_eq!(
        lookup.target().identity().type_name(),
        core::any::type_name::<Organization>()
    );
    assert_eq!(lookup.target_field().segments(), &["id"]);

    let secret = metadata.field("secret").expect("secret metadata");
    assert!(matches!(
        secret.attribute(AttributeKind::Codec),
        Some(AttributeMetadata::Codec(codec)) if codec.name() == "encrypted"
    ));
    assert!(matches!(
        secret.attribute(AttributeKind::Generator),
        Some(AttributeMetadata::Generator(generator))
            if generator.name() == "account_balance"
    ));
}

#[allow(dead_code)]
#[Model(
    id = "test.derive.ReferenceWithOpaqueForeignKey",
    no_clone,
    no_debug,
    no_display,
    no_partial_eq,
    no_hash,
    no_serialize,
    no_deserialize
)]
struct ReferenceWithOpaqueForeignKey {
    #[reference(entity = "test.derive.Organization", property = id)]
    organization_id: std::path::PathBuf,
}

#[test]
fn test_reference_field_auto_opaque_for_non_has_type_shape() {
    let metadata = metadata_of::<ReferenceWithOpaqueForeignKey>();
    let field = metadata.field("organization_id").expect("organization_id metadata");
    assert!(matches!(field.field_type().shape(), TypeShape::Opaque));
    assert_eq!(
        field.field_type().type_name(),
        core::any::type_name::<std::path::PathBuf>()
    );

    let organization = metadata_of::<AttributedModel>()
        .field("organization")
        .expect("organization metadata");
    assert!(matches!(organization.field_type().shape(), TypeShape::Named(_)));
}

#[test]
fn test_derive_registers_every_supported_shape_and_legacy_macro() {
    let registry = ModelRegistry::try_global().expect("the test models should register without duplicate IDs");
    for (id, rust_type_name) in [
        ("test.derive.User", "User"),
        ("test.derive.Empty", "Empty"),
        ("test.derive.UserId", "UserId"),
        ("test.derive.Status", "Status"),
    ] {
        let registration = registry
            .registration(id)
            .unwrap_or_else(|| panic!("the model with ID {id} should be registered"));
        assert_eq!(registration.metadata().id().as_str(), id);
        assert_eq!(registration.rust_type_name(), rust_type_name);
    }
}

#[test]
fn test_derive_exposes_explicit_model_registration() {
    let registration = Status::model_registration();

    assert_eq!(registration.id().as_str(), "test.derive.Status");
    assert!(core::ptr::eq(registration.metadata(), metadata_of::<Status>(),));
}

#[test]
fn test_opaque_field_does_not_require_has_type_shape() {
    let field = metadata_of::<AttributedModel>()
        .field("external")
        .expect("external metadata");

    assert!(matches!(field.field_type().shape(), TypeShape::Opaque));
    assert_eq!(field.field_type().type_name(), core::any::type_name::<ExternalValue>());
}
