// =============================================================================
//    Copyright (c) 2025 - 2026 Haixing Hu.
//
//    SPDX-License-Identifier: Apache-2.0
//
//    Licensed under the Apache License, Version 2.0.
// =============================================================================

//! Integration tests for runtime metadata generated by the `Model` attribute.

use std::collections::HashMap;

use model_runtime::AttributeKind;
use model_runtime::AttributeMetadata;
use model_runtime::AttributeQuery;
use model_runtime::DecimalSemantic;
use model_runtime::HasModelRegistration;
use model_runtime::HasTypeShape;
use model_runtime::ModelRegistry;
use model_runtime::RoundingMode;
use model_runtime::TemporalNormalization;
use model_runtime::TemporalPrecision;
use model_runtime::TextFormat;
use model_runtime::TextRepertoire;
use model_runtime::TypeCapabilities;
use model_runtime::TypeKind;
use model_runtime::TypeShape;
use model_runtime::UniqueComparison;
use model_runtime::metadata_of;
use qubit_model_derive::Enum;
use qubit_model_derive::Model;

#[allow(dead_code)]
#[Model(id = "test.derive.User")]
struct User {
    #[field(identifier(generated))]
    id: Option<i64>,
    #[field(unique(ignore_case))]
    nickname: Option<String>,
}

#[allow(dead_code)]
#[Model(id = "test.derive.ScopedUnique")]
struct ScopedUnique {
    organization_id: i64,
    #[field(unique(respectTo = [organization_id]))]
    code: String,
}

#[allow(dead_code)]
#[Model(id = "test.derive.NumericUnique")]
struct NumericUnique {
    #[field(unique)]
    value: i64,
}

#[Model(id = "test.derive.Empty")]
struct Empty;

#[Model(id = "test.derive.UserId")]
#[allow(dead_code)]
struct UserId(i64);

#[Model(id = "test.derive.DisplayName")]
#[allow(dead_code)]
struct DisplayName(String);

#[Model(id = "test.derive.Phone", textual)]
#[allow(dead_code)]
struct Phone {
    country_area: Option<String>,
    city_area: Option<String>,
    number: String,
}

#[Model(id = "test.derive.PhoneLoginParams")]
#[allow(dead_code)]
struct PhoneLoginParams {
    #[field(text(format = mobile))]
    mobile: Option<Phone>,
}

#[Enum(id = "test.derive.Status")]
#[allow(dead_code)]
enum Status {
    Draft,
    Published,
}

#[Enum(id = "test.derive.SerializedStatus")]
enum SerializedStatus {
    #[serde(rename = "reviewing")]
    Reviewing,
    #[serde(rename(serialize = "invalid-state"))]
    Invalid,
}

#[allow(dead_code)]
#[Model(id = "test.derive.Organization")]
struct Organization {
    id: i64,
}

struct ExternalValue;

#[allow(dead_code)]
#[Model(id = "test.derive.OpaqueContainer")]
struct OpaqueContainer {
    #[field(opaque)]
    external_values: Option<Vec<i128>>,
}

#[allow(dead_code)]
#[Model(
    id = "test.derive.AttributedModel",
    no_clone,
    no_debug,
    no_display,
    no_eq,
    no_partial_eq,
    no_hash,
    no_serialize,
    no_deserialize,
    primary_key(fields(id), generated(id)),
    index(name = "created_at_index", fields(created_at)),
    key(name = "account", fields(organization_id, username)),
    ownership(owner = Organization)
)]
struct AttributedModel {
    id: i64,
    #[field(reference(
        target = "test.derive.Organization",
        target_field = id,
        must_exist = true,
        same_as = "organization.id"
    ))]
    organization_id: i64,
    organization: Organization,
    #[field(lookup_relation(target = Organization, target_field = id))]
    organization_lookup: i64,
    #[field(text(
        min_chars = 3,
        max_chars = 32,
        min_bytes = 3,
        max_bytes = 64,
        repertoire = ascii,
        non_blank,
        format = email
    ))]
    #[field(unique(
        name = "organization_username",
        respectTo = [organization_id],
        ignoreCase = true
    ))]
    username: String,
    #[field(sequence(min_items = 1, max_items = 5, unique_items))]
    aliases: Vec<String>,
    #[field(element(text(repertoire = ascii)))]
    ascii_codes: [String; 2],
    #[field(map(min_entries = 1, max_entries = 4))]
    labels: HashMap<String, String>,
    #[field(time(precision = millisecond, normalization = utc))]
    created_at: chrono::DateTime<chrono::Utc>,
    #[field(decimal(precision = 8, scale = 3, rounding = half_up))]
    ratio: bigdecimal::BigDecimal,
    #[field(money(precision = 12, scale = 2, rounding = half_even))]
    balance: bigdecimal::BigDecimal,
    #[field(element(decimal(scale = 2)))]
    decimal_values: Vec<bigdecimal::BigDecimal>,
    #[field(text(format = mobile))]
    mobile: String,
    #[field(codec = "encrypted", generator(name = "account_balance"))]
    secret: String,
    verification_code: String,
    #[field(opaque)]
    external: ExternalValue,
}

/// Verifies that the derive macro preserves the declared stable model ID.
#[test]
fn test_derive_emits_declared_model_id() {
    assert_eq!(metadata_of::<User>().id().as_str(), "test.derive.User");
}

#[test]
fn test_derive_emits_declared_fields_and_nullable_shape() {
    let metadata = metadata_of::<User>();

    assert_eq!(metadata.fields().count(), 2);
    assert!(metadata.field("nickname").expect("nickname metadata").is_nullable());
}

#[test]
fn test_derive_preserves_opaque_container_shape() {
    let field = metadata_of::<OpaqueContainer>()
        .field("external_values")
        .expect("opaque container field metadata");

    assert!(field.is_nullable());
    assert!(matches!(
        field.field_type().shape(),
        TypeShape::Optional(inner)
            if matches!(inner.shape(), TypeShape::Sequence(element)
                if matches!(element.shape(), TypeShape::Opaque))
    ));
}

#[test]
fn test_shorthand_normalizes_to_type_constraints() {
    let metadata = metadata_of::<User>();

    let primary_key = metadata.primary_key().expect("primary key");
    assert_eq!(
        primary_key
            .fields()
            .iter()
            .map(|field| field.name())
            .collect::<Vec<_>>(),
        ["id"]
    );
    assert!(primary_key.fields()[0].is_generated());

    let unique = metadata.unique_constraints().next().expect("unique metadata");
    assert_eq!(
        unique
            .fields()
            .iter()
            .map(|field| (field.name(), field.comparison()))
            .collect::<Vec<_>>(),
        [("nickname", UniqueComparison::IgnoreCase)]
    );

    assert_eq!(metadata.indexes().count(), 0);
}

#[test]
fn test_field_unique_respect_to_expands_as_ordered_composite_constraint() {
    let unique = metadata_of::<ScopedUnique>()
        .unique_constraints()
        .next()
        .expect("scoped unique metadata");
    assert_eq!(
        unique
            .fields()
            .iter()
            .map(|field| (field.name(), field.comparison()))
            .collect::<Vec<_>>(),
        [
            ("organization_id", UniqueComparison::Exact),
            ("code", UniqueComparison::IgnoreCase),
        ]
    );
}

#[test]
fn test_non_text_field_unique_defaults_to_exact_comparison() {
    let unique = metadata_of::<NumericUnique>()
        .unique_constraints()
        .next()
        .expect("numeric unique metadata");
    assert_eq!(unique.comparison_of("value"), Some(UniqueComparison::Exact));
}

#[test]
fn test_derive_emits_empty_struct_metadata() {
    let metadata = metadata_of::<Empty>();

    assert!(matches!(metadata.kind(), TypeKind::Struct(_)));
    assert_eq!(metadata.fields().count(), 0);
}

#[test]
fn test_derive_emits_newtype_metadata() {
    let metadata = metadata_of::<UserId>();

    assert!(matches!(metadata.kind(), TypeKind::Newtype(newtype)
        if newtype.field().ordinal() == 0
            && newtype.field().name() == "0"
            && newtype.field().rust_type_name() == "i64"));
}

#[test]
fn test_derive_newtype_inherits_inner_type_capabilities() {
    assert_eq!(<DisplayName as HasTypeShape>::CAPABILITIES, TypeCapabilities::TEXT);
}

#[test]
fn test_textual_named_model_accepts_mobile_constraints() {
    assert_eq!(<Phone as HasTypeShape>::CAPABILITIES, TypeCapabilities::TEXT);
    assert!(matches!(
        metadata_of::<PhoneLoginParams>()
            .field("mobile")
            .expect("mobile field metadata")
            .text_constraint(),
        Some(constraint) if constraint.format() == Some(TextFormat::Mobile)
    ));
}

#[test]
fn test_derive_emits_fieldless_enum_metadata() {
    let metadata = metadata_of::<Status>();

    assert!(matches!(metadata.kind(), TypeKind::Enum(enum_metadata)
        if enum_metadata.variants().len() == 2
            && enum_metadata.variants()[0].name() == "DRAFT"
            && enum_metadata.variants()[1].ordinal() == 1));
}

#[test]
fn test_enum_name_methods_follow_serde_serialization_names() {
    assert_eq!(SerializedStatus::Reviewing.name(), "reviewing");
    assert_eq!(
        SerializedStatus::from_name("reviewing"),
        Some(SerializedStatus::Reviewing)
    );
    assert_eq!(SerializedStatus::Invalid.name(), "invalid-state");
    assert_eq!(
        SerializedStatus::from_name("invalid-state"),
        Some(SerializedStatus::Invalid)
    );
    assert_eq!(SerializedStatus::from_name("invalid"), None);
}

#[test]
fn test_model_attributes_expand_in_canonical_form() {
    let metadata = metadata_of::<AttributedModel>();

    let primary_key = metadata.primary_key().expect("primary key metadata");
    assert_eq!(
        primary_key
            .fields()
            .iter()
            .map(|field| (field.name(), field.is_generated()))
            .collect::<Vec<_>>(),
        [("id", true)]
    );
    let unique = metadata.unique_constraints().next().expect("unique metadata");
    assert_eq!(unique.name(), Some("organization_username"));
    assert_eq!(unique.comparison_of("organization_id"), Some(UniqueComparison::Exact));
    assert_eq!(unique.comparison_of("username"), Some(UniqueComparison::IgnoreCase));
    let index = metadata
        .indexes()
        .find(|index| index.name() == Some("created_at_index"))
        .expect("created-at index metadata");
    assert_eq!(index.name(), Some("created_at_index"));
    assert_eq!(index.fields(), &["created_at"]);
    assert!(metadata.indexes().any(|index| index.fields() == ["organization_id"]));
    assert!(matches!(
        metadata.attribute(AttributeKind::Key),
        Some(AttributeMetadata::Key(key))
            if key.name() == Some("account") && key.contains("username")
    ));
    assert!(matches!(
        metadata.attribute(AttributeKind::Ownership),
        Some(AttributeMetadata::Ownership(ownership))
            if ownership.owner().identity().type_name()
                == core::any::type_name::<Organization>()
    ));
}

#[test]
fn test_text_sequence_and_map_attributes_expand() {
    let metadata = metadata_of::<AttributedModel>();
    let text = metadata
        .field("username")
        .expect("username metadata")
        .text_constraint()
        .expect("text constraint");
    assert_eq!(text.min_chars(), Some(3));
    assert_eq!(text.max_chars(), Some(32));
    assert_eq!(text.min_bytes(), Some(3));
    assert_eq!(text.max_bytes(), Some(64));
    assert_eq!(text.repertoire(), TextRepertoire::Ascii);
    assert!(text.is_non_blank());
    assert_eq!(text.format(), Some(TextFormat::Email));

    assert!(matches!(
        metadata
            .field("aliases")
            .expect("aliases metadata")
            .attribute(AttributeKind::Sequence),
        Some(AttributeMetadata::Sequence(sequence))
            if sequence.min_items() == Some(1)
                && sequence.max_items() == Some(5)
                && sequence.has_unique_items()
    ));
    assert!(matches!(
        metadata
            .field("labels")
            .expect("labels metadata")
            .attribute(AttributeKind::Map),
        Some(AttributeMetadata::Map(map))
            if map.min_entries() == Some(1) && map.max_entries() == Some(4)
    ));
}

#[test]
fn test_temporal_decimal_and_money_attributes_expand() {
    let metadata = metadata_of::<AttributedModel>();

    assert!(matches!(
        metadata
            .field("created_at")
            .expect("created_at metadata")
            .attribute(AttributeKind::Temporal),
        Some(AttributeMetadata::Temporal(temporal))
            if temporal.precision() == TemporalPrecision::Millisecond
                && temporal.normalization() == TemporalNormalization::Utc
    ));
    assert!(matches!(
        metadata
            .field("ratio")
            .expect("ratio metadata")
            .attribute(AttributeKind::Decimal),
        Some(AttributeMetadata::Decimal(decimal))
            if decimal.precision() == Some(8)
                && decimal.scale() == 3
                && decimal.rounding() == RoundingMode::HalfUp
                && decimal.semantic() == DecimalSemantic::Number
    ));
    assert!(matches!(
        metadata
            .field("balance")
            .expect("balance metadata")
            .attribute(AttributeKind::Decimal),
        Some(AttributeMetadata::Decimal(decimal))
            if decimal.precision() == Some(12)
                && decimal.scale() == 2
                && decimal.rounding() == RoundingMode::HalfEven
                && decimal.semantic() == DecimalSemantic::Money
    ));
}

#[test]
fn test_migrated_element_and_mobile_constraints_expand() {
    let metadata = metadata_of::<AttributedModel>();
    let ascii_element = metadata
        .field("ascii_codes")
        .expect("ascii_codes metadata")
        .element_metadata()
        .expect("ASCII element metadata");
    assert!(matches!(
        ascii_element.attributes(),
        [AttributeMetadata::Text(text)]
            if text.repertoire() == TextRepertoire::Ascii
    ));

    let decimal_element = metadata
        .field("decimal_values")
        .expect("decimal_values metadata")
        .element_metadata()
        .expect("decimal element metadata");
    assert!(matches!(
        decimal_element.attributes(),
        [AttributeMetadata::Decimal(decimal)]
            if decimal.scale() == 2
                && decimal.semantic() == DecimalSemantic::Number
    ));

    assert_eq!(
        metadata
            .field("mobile")
            .expect("mobile metadata")
            .text_constraint()
            .and_then(|text| text.format()),
        Some(TextFormat::Mobile)
    );
}

#[test]
fn test_reference_and_strategy_attributes_expand() {
    let metadata = metadata_of::<AttributedModel>();
    let reference = metadata
        .field("organization_id")
        .expect("organization_id metadata")
        .reference()
        .expect("reference metadata");
    assert_eq!(reference.target().as_str(), "test.derive.Organization");
    assert_eq!(reference.target_field().segments(), &["id"]);
    assert!(reference.must_exist());
    assert_eq!(
        reference.same_as().expect("same-as path").segments(),
        &["organization", "id"]
    );

    let lookup = metadata
        .field("organization_lookup")
        .expect("organization lookup metadata")
        .lookup_relation()
        .expect("lookup relation metadata");
    assert_eq!(
        lookup.target().identity().type_name(),
        core::any::type_name::<Organization>()
    );
    assert_eq!(lookup.target_field().segments(), &["id"]);

    let secret = metadata.field("secret").expect("secret metadata");
    assert!(matches!(
        secret.attribute(AttributeKind::Codec),
        Some(AttributeMetadata::Codec(codec)) if codec.name() == "encrypted"
    ));
    assert!(matches!(
        secret.attribute(AttributeKind::Generator),
        Some(AttributeMetadata::Generator(generator))
            if generator.name() == "account_balance"
    ));
}

#[test]
fn test_derive_registers_every_supported_shape_and_legacy_macro() {
    let registry = ModelRegistry::try_global().expect("the test models should register without duplicate IDs");
    for (id, rust_type_name) in [
        ("test.derive.User", "User"),
        ("test.derive.Empty", "Empty"),
        ("test.derive.UserId", "UserId"),
        ("test.derive.Status", "Status"),
    ] {
        let registration = registry
            .registration(id)
            .unwrap_or_else(|| panic!("the model with ID {id} should be registered"));
        assert_eq!(registration.metadata().id().as_str(), id);
        assert_eq!(registration.rust_type_name(), rust_type_name);
    }
}

#[test]
fn test_derive_exposes_explicit_model_registration() {
    let registration = Status::model_registration();

    assert_eq!(registration.id().as_str(), "test.derive.Status");
    assert!(core::ptr::eq(registration.metadata(), metadata_of::<Status>(),));
}

#[test]
fn test_opaque_field_does_not_require_has_type_shape() {
    let field = metadata_of::<AttributedModel>()
        .field("external")
        .expect("external metadata");

    assert!(matches!(field.field_type().shape(), TypeShape::Opaque));
    assert_eq!(field.field_type().type_name(), core::any::type_name::<ExternalValue>());
}
